Hayabusa nirs clean
DOI-USGS/ale pull request #532
Opened 2023-05-12 20:10 UTC by jrcain-usgs

Redo of previous PR without absolute paths.

One of the tests may fail because of the projection/geotransform bug, addressed in #528

2023-05-13 01:00 UTC, acpaquette requested changes
Overall looks great! Just need a changelog entry and this can get merged

2023-05-18 17:16 UTC, jrcain-usgs commented
Changelog entry added.

2023-05-18 20:37 UTC, acpaquette commented
@jrcain-usgs looks like the nirs test is failing now due to the merge of the projection fix. Can the test here be updated? You should just need to remove the projection and geotransform keywords in the truth ISD

2023-05-19 19:19 UTC, acpaquette approved these changes

2023-05-26 22:23 UTC, acpaquette approved these changes

2023-05-26 22:23 UTC, merged