Mariner10 driver and test
DOI-USGS/ale pull request #547
Opened 2023-06-15 18:09 UTC by chkim-usgs

Added Mariner10 driver and tests.

Some insight:
-  Added `NoDistortion` mixin as Viking and Voyager have `NoDistortion` in ALE despite both having `ReseauDistortionMap` in ISIS ([ISIS Mariner10 example](https://github.com/DOI-USGS/ISIS3/blob/dev/isis/src/mariner/objs/Mariner10Camera/Mariner10Camera.cpp#L106))
- `sensor_frame_id` is hard-coded to the [frame id in ISIS Mariner10](https://github.com/DOI-USGS/ISIS3/blob/dev/isis/src/mariner/objs/Mariner10Camera/Mariner10Camera.cpp#L53)
- `ephemeris_start_time` is calculated based off of the [shutter open time calculation in ISIS Mariner10](https://github.com/DOI-USGS/ISIS3/blob/dev/isis/src/mariner/objs/Mariner10Camera/Mariner10Camera.cpp#L147)

Tested with: `python -m pytest tests/pytests/test_mariner_drivers.py`

2023-06-15 21:00 UTC, acpaquette requested changes
Overall looks great! Nice job on figuring out the driver structure along with the mixins. Just a few things to address before we can merge it in!

2023-06-16 14:21 UTC, chkim-usgs commented on ale/drivers/mariner_drivers.py
> +        return inst_id_lookup[super().instrument_id]
I updated the `inst_id_lookup` to return `M10_Spacecraft` for both ids.
However, here are some errors I got from removing `ikid` and `sensor_frame_id`:
- Remove both properties: In `to_isd()` func in formatter.py, errors occurs at retrieving `focal_length` --> `Spice returns not found for function: gdpool`
- Define `sensor_frame_id` but remove `ikid`: same error as above
- Define `ikid` but remove `sensor_frame_id`: In `to_isd()` func in formatter.py, error occurs at retrieving `frame_chain` --> `The ck rotation from frame -76110 cannot be found due to no pointing available at requested time -812916168.4069488 or a problem with the frame`

Is there something I should look further into or is it okay to leave these properties in the Mariner10 driver?

2023-06-16 19:12 UTC, acpaquette commented on ale/drivers/mariner_drivers.py
> +        return inst_id_lookup[super().instrument_id]
Seems like it can stay as it is then!

2023-06-16 19:14 UTC, acpaquette submitted a review, later dismissed
Generally speaking things look good! Were you able to compare it to the original spice data? That is, did you compare an `isis` source spiceinit'd cube against an `ale` source spiceinit'd cube

2023-06-16 19:32 UTC, chkim-usgs commented
@acpaquette would that be [Step 7 of the Step-by-Step](https://github.com/DOI-USGS/ale/wiki/Step-By-Step-ALE-Driver-Creation)? I've run `spiceinit` after creating the new driver but I still got `source=isis` and no errors. I did a `cmake ..` and `make` ([Building ALE](https://github.com/DOI-USGS/ale#building-ale)) to make sure the changes took effect, but is there something else I need to do for `spiceinit` to pick up the changes? Oh, would it be [adding ALE as a dependency](https://github.com/DOI-USGS/ale#adding-ale-as-a-dependency)?

2023-07-17 21:53 UTC, acpaquette commented
@chkim-usgs Could we get an addition to the change log? After that this should be good to go!

2023-07-18 20:26 UTC, acpaquette approved these changes

2023-07-18 20:26 UTC, merged