Spiceypy
DOI-USGS/ale pull request #578
Opened 2023-11-14 20:13 UTC by Kelvinrr

I'll put in a PR into the recipe as well. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2023-11-14 20:22 UTC, Kelvinrr commented
@acpaquette I think this would require a new ALE major release? Technically this change is breaking potentially for some people because the change in spiceypy. In which case, I can update this with a version tick for ALE.

2023-11-15 21:00 UTC, acpaquette requested changes
There may also be a version defined in the CmakeLists.txt file at the root of the repo

2023-11-15 21:00 UTC, acpaquette commented on code.json
> +      "email": "jlaura@usgs.gov"
I don't think Jay should remain the point of contact here, either myself or potentially @Kelvinrr

2023-11-17 22:34 UTC, acpaquette approved these changes

2023-11-20 15:37 UTC, merged